# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 16, 9, 50, 18, 116932, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 16, 9, 50, 22, 903849, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
