# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160816_0950'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together=set([('follower', 'followee')]),
        ),
    ]
