# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('notifications', '0010_auto_20161015_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
    ]
