# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
