# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_post_is_marked_for_removal'),
        ('notifications', '0018_auto_20161117_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifaication_parent', to='posts.PostComment'),
        ),
    ]
