# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160629_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=set([('user', 'post')]),
        ),
    ]
