# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-03 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160629_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default=1, upload_to=posts.models.post_upload_dir),
            preserve_default=False,
        ),
    ]
