# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-03 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160703_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postvote',
            old_name='is_voted',
            new_name='is_positive',
        ),
    ]
