# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160703_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='is_positive',
            field=models.NullBooleanField(),
        ),
    ]
