# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Report reason'),
        ),
    ]
