# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-20 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20160720_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.post_upload_dir),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.post_upload_dir),
        ),
    ]
