# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20160721_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expired_at',
            field=models.DateTimeField(default=posts.models.get_expiration_date),
        ),
    ]
