# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-22 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_hidden',
        ),
    ]
