# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_postcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
