# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-09 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvoted_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='voted_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
