# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-15 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20160809_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvoted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='voted_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
