# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20160820_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_anonymous',
        ),
    ]
