# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-29 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20161011_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
