# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20161029_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
