# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20161029_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_marked_for_removal',
            field=models.BooleanField(default=False),
        ),
    ]
