# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('users', '0007_auto_20160625_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
            preserve_default=False,
        ),
    ]
