# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-26 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirm',
        ),
    ]
