# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160626_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_my_blasts', models.BooleanField(default=True)),
                ('notify_upvoted_blasts', models.BooleanField(default=False)),
                ('notify_downvoted_blasts', models.BooleanField(default=False)),
                ('notify_pinned_blasts', models.BooleanField(default=False)),
                ('notify_votes', models.BooleanField(default=True)),
                ('notify_comments', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('notify_reblasts', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
