# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notify_comments',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notify_reblasts',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
        ),
    ]
