# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, default=None, help_text='Use 1 for male and 0 for female', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Is user account in private mode?'),
        ),
    ]
