# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_pinned_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pinned_posts',
            field=models.ManyToManyField(blank=True, related_name='users', to='posts.Post'),
        ),
    ]
