# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20160711_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatars_upload_dir),
        ),
    ]
