# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-22 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_post_is_hidden'),
        ('users', '0019_usersettings_notify_new_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden_posts',
            field=models.ManyToManyField(blank=True, related_name='hidden_users', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pinned_posts',
            field=models.ManyToManyField(blank=True, related_name='pinned_users', to='posts.Post'),
        ),
    ]
