# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-26 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20160826_0821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedusers',
            unique_together=set([('user', 'blocked')]),
        ),
    ]
