# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-29 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20160826_0826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('follower', 'followee')]),
        ),
    ]
