# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('users', '0029_auto_20160829_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinned_tags',
            field=models.ManyToManyField(blank=True, related_name='pinned_users', to='tags.Tag'),
        ),
    ]
