# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_pinned_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
