# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_remove_post_is_anonymous'),
        ('users', '0033_user_search_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_posts', to='posts.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='pinned_posts',
        ),
        migrations.AddField(
            model_name='pinnedposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_pinned',
            field=models.ManyToManyField(blank=True, related_name='pinned_users', through='users.PinnedPosts', to='posts.Post'),
        ),
    ]
