# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20161007_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posts_pinned',
            new_name='pinned_posts',
        ),
        migrations.AlterField(
            model_name='pinnedposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='pinnedposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinners', to=settings.AUTH_USER_MODEL),
        ),
    ]
