# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20161008_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.IntegerField(choices=[(0, 'Other'), (1, 'Sensitive content'), (2, 'spam'), (3, 'Duplicated content'), (4, 'Bulling'), (5, 'Intel violation')], help_text='Report reason')),
                ('text', models.CharField(blank=True, help_text='Details', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='sended_reports')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='related_reports')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pinnedposts',
            options={'verbose_name': 'Pinned post', 'verbose_name_plural': 'Pinned posts'},
        ),
    ]
