# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20161010_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Sensitive content'), (2, 'Spam'), (3, 'Duplicated content'), (4, 'Bulling'), (5, 'Intel violation')], help_text='Report reason'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
