# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20161011_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
