# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.IntegerField(choices=[(0, 'Other'), (1, 'Sensitive content'), (2, 'Spam'), (3, 'Duplicated content'), (4, 'Bulling'), (5, 'Intel violation')], help_text='Report reason')),
                ('text', models.CharField(blank=True, help_text='Details', max_length=128)),
                ('object_pk', models.PositiveIntegerField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_report', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'get_latest_by': 'created_at',
                'verbose_name': 'Report',
            },
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('content_type', 'object_pk')]),
        ),
    ]
