# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([]),
        ),
    ]
