# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsconfirmation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneconfirmation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phoneconfirmation',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
