# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import smsconfirmation.models


class Migration(migrations.Migration):

    dependencies = [
        ('smsconfirmation', '0002_auto_20160625_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneconfirmation',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='phoneconfirmation',
            name='code',
            field=models.CharField(default=smsconfirmation.models.get_phone_confirmation_code, max_length=4),
        ),
    ]
