# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsconfirmation', '0003_auto_20160625_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneconfirmation',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'Phone confirmation'), (2, 'Reset password')], default=1),
            preserve_default=False,
        ),
    ]
