# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsconfirmation', '0005_auto_20160702_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneconfirmation',
            options={'ordering': ('-created_at',)},
        ),
    ]
